// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file diagnostics.proto (package diagnostics, syntax proto3)
/* eslint-disable */

import type { Message } from '@bufbuild/protobuf';
import type {
	GenFile,
	GenMessage,
	GenService,
	} from '@bufbuild/protobuf/codegenv2';
import { messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import { file_diagnostics as serverFileDiagnostics } from '../../../example-grpc-server/src/generated/diagnostics_pb.ts';

/**
	 * Describes the file diagnostics.proto.
	 *
	 * For the web client, we reuse the canonical file descriptor generated for the
	 * example gRPC server to avoid descriptor drift between the two examples.
	 */
export const file_diagnostics: GenFile = serverFileDiagnostics;

/**
 * Request to retrieve a diagnostics snapshot.
 *
 * @generated from message diagnostics.GetDiagnosticsSnapshotRequest
 */
export type GetDiagnosticsSnapshotRequest = Message<
  'diagnostics.GetDiagnosticsSnapshotRequest'
> & {
  /**
   * Time window in seconds to analyze. If zero, server uses its default.
   *
   * @generated from field: int32 window_seconds = 1;
   */
  windowSeconds: number;

  /**
   * Maximum number of blobs to include. If zero, server uses its default.
   *
   * @generated from field: int32 max_blobs = 2;
   */
  maxBlobs: number;

  /**
   * Minimum severity that will cause a blob to be considered degraded.
   * Valid values are: "debug", "info", "warn", "error".
   *
   * @generated from field: string severity_threshold = 3;
   */
  severityThreshold: string;
};

/**
 * Describes the message diagnostics.GetDiagnosticsSnapshotRequest.
 * Use `create(GetDiagnosticsSnapshotRequestSchema)` to create a new message.
 */
export const GetDiagnosticsSnapshotRequestSchema: GenMessage<
  GetDiagnosticsSnapshotRequest
> = /*@__PURE__*/ messageDesc(file_diagnostics, 0);

/**
 * Per-blob summary of diagnostics over the window.
 *
 * @generated from message diagnostics.DiagnosticsBlobSummary
 */
export type DiagnosticsBlobSummary = Message<
  'diagnostics.DiagnosticsBlobSummary'
> & {
  /**
   * @generated from field: string blob_name = 1;
   */
  blobName: string;

  /**
   * healthy | degraded | failing
   *
   * @generated from field: string health = 2;
   */
  health: string;

  /**
   * @generated from field: int64 total_events = 3;
   */
  totalEvents: bigint;

  /**
   * @generated from field: int64 error_count = 4;
   */
  errorCount: bigint;

  /**
   * @generated from field: int64 warn_count = 5;
   */
  warnCount: bigint;

  /**
   * @generated from field: int64 info_count = 6;
   */
  infoCount: bigint;

  /**
   * @generated from field: int64 debug_count = 7;
   */
  debugCount: bigint;

  /**
   * @generated from field: int64 success_count = 8;
   */
  successCount: bigint;

  /**
   * @generated from field: int64 failure_count = 9;
   */
  failureCount: bigint;

  /**
   * @generated from field: double average_duration_ms = 10;
   */
  averageDurationMs: number;

  /**
   * @generated from field: double p95_duration_ms = 11;
   */
  p95DurationMs: number;

  /**
   * @generated from field: string last_error_message = 12;
   */
  lastErrorMessage: string;

  /**
   * @generated from field: string last_error_timestamp = 13;
   */
  lastErrorTimestamp: string;
};

/**
 * Describes the message diagnostics.DiagnosticsBlobSummary.
 * Use `create(DiagnosticsBlobSummarySchema)` to create a new message.
 */
export const DiagnosticsBlobSummarySchema: GenMessage<DiagnosticsBlobSummary> =
  /*@__PURE__*/ messageDesc(file_diagnostics, 1);

/**
 * Response with the overall diagnostics snapshot and summaries.
 *
 * @generated from message diagnostics.GetDiagnosticsSnapshotResponse
 */
export type GetDiagnosticsSnapshotResponse = Message<
  'diagnostics.GetDiagnosticsSnapshotResponse'
> & {
  /**
   * @generated from field: string generated_at = 1;
   */
  generatedAt: string;

  /**
   * @generated from field: int32 window_seconds = 2;
   */
  windowSeconds: number;

  /**
   * @generated from field: int64 total_events = 3;
   */
  totalEvents: bigint;

  /**
   * @generated from field: repeated diagnostics.DiagnosticsBlobSummary blobs = 4;
   */
  blobs: DiagnosticsBlobSummary[];

  /**
   * Optional pre-rendered human-readable summary text, optimized for LLMs.
   *
   * @generated from field: string summary_text = 5;
   */
  summaryText: string;
};

/**
 * Describes the message diagnostics.GetDiagnosticsSnapshotResponse.
 * Use `create(GetDiagnosticsSnapshotResponseSchema)` to create a new message.
 */
export const GetDiagnosticsSnapshotResponseSchema: GenMessage<
  GetDiagnosticsSnapshotResponse
> = /*@__PURE__*/ messageDesc(file_diagnostics, 2);

/**
 * DiagnosticsService exposes a summarized, blob-centric view of recent
 * application activity for debugging and observability.
 *
 * @generated from service diagnostics.DiagnosticsService
 */
export const DiagnosticsService: GenService<{
  /**
   * Get a snapshot of recent diagnostics activity grouped by blob.
   *
   * @generated from rpc diagnostics.DiagnosticsService.GetDiagnosticsSnapshot
   */
  getDiagnosticsSnapshot: {
    methodKind: 'unary';
    input: typeof GetDiagnosticsSnapshotRequestSchema;
    output: typeof GetDiagnosticsSnapshotResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_diagnostics, 0);

